POST http://localhost:8080/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InBhdWxAZ21haWwuY29tIiwiZXhwIjoxNzYyNzk4NjU5LCJyb2xlIjoiaW5zdHJ1Y3RvciIsInVzZXJJZCI6MTJ9.vepz-lp0Pv2tQp0VxME-Mfn6L-RAJNrzEkV9X2RAkOw

{
    "title": "Object Oriented Design",
    "description": "Everything there is to it, I will teach you!",
    "category": "computer science"
}