POST http://localhost:8080/courses/2/lessons
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG5AZ21haWwuY29tIiwiZXhwIjoxNzYzNjExMjQ2LCJyb2xlIjoiaW5zdHJ1Y3RvciIsInVzZXJJZCI6MX0.HsUKDVf8aMbOyddV9TZgVaNTl-jZITvdlkNbQqLVSxQ

{
    "title": "Lesson 2: Setting Up Your Development Environment",
    "content": "In this lesson, you will learn how to prepare your computer for web development. You will install a code editor, understand what extensions and themes are, and learn how to organize project files. You will also be introduced to the browser developer tools used to inspect and debug web pages."
}
