POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "firstName": "Saugat",
    "lastName": "Adhikari",
    "email": "saugat@gmail.com",
    "password": "saugat123",
    "role": "student"
}