POST http://localhost:8080/auth/register
Content-Type: application/json

{
    "firstName": "hero",
    "lastName": "hai",
    "email": "hero@gmail.com",
    "password": "hero123",
    "role": "student"
}