GET http://localhost:8080/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxvbkBnbWFpbC5jb20iLCJleHAiOjE3NjE4MTA3MzIsInVzZXJJZCI6MTF9.Y_dbyhfnecCiiSKanFgj2bDz4AEBtlmN20hnNhoAzos